apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argodemo-web
spec:
  ingressClassName: cloudflare
  rules:
    - host: argodemo-web.coregatekit.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argodemo-web
                port:
                  number: 3000
