apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: argodemo-web
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: argodemo-web

images:
  - name: ghcr.io/coregatekit/coregatekit/argo-demo-web
    newTag: latest
